// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POE_TEST_ONE.Data;

#nullable disable

namespace POE_TEST_ONE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POE_TEST_ONE.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Class_hours_per_week")
                        .HasColumnType("int");

                    b.Property<int>("Hours_Studied_On_CertinDate")
                        .HasColumnType("int");

                    b.Property<string>("Module_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Module_code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Num_credits")
                        .HasColumnType("int");

                    b.Property<int>("Num_weeks_in_semester")
                        .HasColumnType("int");

                    b.Property<int>("Remaining_study_hours")
                        .HasColumnType("int");

                    b.Property<int>("Self_Study_hours")
                        .HasColumnType("int");

                    b.Property<DateTime>("Semester_start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Studied_on_certin_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
